version: '3.8'

networks:
  trackyourhealth:

services:
  oathkeeper:
    container_name: oathkeeper
    image: oryd/oathkeeper:v0.38
    depends_on:
      - kratos
    ports:
      - 8080:4455
      - 4456:4456
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    restart: on-failure
    networks:
      - trackyourhealth
    volumes:
      - ./ory/oathkeeper:/etc/config/oathkeeper

  trackyourhealth-api:
    container_name: trackyourhealth-api
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - trackyourhealth-db
    networks:
      - trackyourhealth

  trackyourhealth-db:
    container_name: trackyourhealth-db
    image: postgres:14.2-alpine
    ports:
      - ${DB_PORT}:5432
    networks:
      - trackyourhealth

  pgadmin:
    container_name: trackyourhealth-pgadmin
    image: dpage/pgadmin4:6.7
    depends_on:
      - trackyourhealth-db
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - trackyourhealth

  kratos:
    container_name: kratos
    image: oryd/kratos:v0.10.1
    depends_on:
      - kratos-db
    networks:
      - trackyourhealth
    environment:
      - DSN=${KRATOS_DB_DSN}
    ports:
      - '4433:4433'
      - '4434:4434'
    volumes:
      - type: bind
        source: ./ory/kratos
        target: /etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier

  kratos-migrate:
    image: oryd/kratos:v0.10.1
    environment:
      - DSN=${KRATOS_DB_DSN}
    networks:
      - trackyourhealth
    volumes:
      - type: bind
        source: ./ory/kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes

  kratos-db:
    container_name: kratos-db
    image: postgres:14.2-alpine
    ports:
      - ${KRATOS_DB_PORT}:5432
    networks:
      - trackyourhealth

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.10.1
    networks:
      - trackyourhealth
    ports:
      - '4455:3000'

volumes:
  data-trackyourhealth-db:
  data-kratos-db:
